// Generated by gencpp from file robotics_hw1/MotorSpeed.msg
// DO NOT EDIT!


#ifndef ROBOTICS_HW1_MESSAGE_MOTORSPEED_H
#define ROBOTICS_HW1_MESSAGE_MOTORSPEED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace robotics_hw1
{
template <class ContainerAllocator>
struct MotorSpeed_
{
  typedef MotorSpeed_<ContainerAllocator> Type;

  MotorSpeed_()
    : header()
    , rpm(0.0)  {
    }
  MotorSpeed_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , rpm(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _rpm_type;
  _rpm_type rpm;





  typedef boost::shared_ptr< ::robotics_hw1::MotorSpeed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotics_hw1::MotorSpeed_<ContainerAllocator> const> ConstPtr;

}; // struct MotorSpeed_

typedef ::robotics_hw1::MotorSpeed_<std::allocator<void> > MotorSpeed;

typedef boost::shared_ptr< ::robotics_hw1::MotorSpeed > MotorSpeedPtr;
typedef boost::shared_ptr< ::robotics_hw1::MotorSpeed const> MotorSpeedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotics_hw1::MotorSpeed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotics_hw1::MotorSpeed_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robotics_hw1::MotorSpeed_<ContainerAllocator1> & lhs, const ::robotics_hw1::MotorSpeed_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.rpm == rhs.rpm;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robotics_hw1::MotorSpeed_<ContainerAllocator1> & lhs, const ::robotics_hw1::MotorSpeed_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robotics_hw1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robotics_hw1::MotorSpeed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotics_hw1::MotorSpeed_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotics_hw1::MotorSpeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotics_hw1::MotorSpeed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotics_hw1::MotorSpeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotics_hw1::MotorSpeed_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotics_hw1::MotorSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "227ff304119c584c2200d7d923efaba9";
  }

  static const char* value(const ::robotics_hw1::MotorSpeed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x227ff304119c584cULL;
  static const uint64_t static_value2 = 0x2200d7d923efaba9ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotics_hw1::MotorSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotics_hw1/MotorSpeed";
  }

  static const char* value(const ::robotics_hw1::MotorSpeed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotics_hw1::MotorSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64 rpm\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::robotics_hw1::MotorSpeed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotics_hw1::MotorSpeed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.rpm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorSpeed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotics_hw1::MotorSpeed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotics_hw1::MotorSpeed_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "rpm: ";
    Printer<double>::stream(s, indent + "  ", v.rpm);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTICS_HW1_MESSAGE_MOTORSPEED_H
